#!/usr/bin/python3

import socket
import sys
import threading

if len(sys.argv) < 2:
    print("Veuillez spécifier un fichier en argument")
    sys.exit(1)

try:
    ip_file = open(sys.argv[1],"r").read()
except:
    print("Error loading IP file")
    sys.exit(1)

def resolve_subdomain(subdomain, ip_addresses):

    try:
        resolved_ip = socket.gethostbyname(subdomain)
        if resolved_ip in ip_addresses:
            print(subdomain)
    except:
        pass

for line in sys.stdin:
    subdomain = line.strip()
    thread = threading.Thread(target=resolve_subdomain, args=(subdomain, ip_file))
    thread.start()

thread.join()
