#!/usr/bin/python3

import socket
import sys
import threading

def resolve_fqdn(fqdn, scope):
    try:
        resolved_fqdn = socket.gethostbyname_ex(fqdn)
        for ip in resolved_fqdn[2]:
            if ip in scope:
                print(fqdn)
    except:
        pass

if len(sys.argv) < 2:
    print("No file provided as argument.")
    sys.exit(1)

try:
    ip_file = open(sys.argv[1],"r").read()
except:
    print("Error loading IP file")
    sys.exit(1)

for line in sys.stdin:
    fqdn = line.strip()
    thread = threading.Thread(target=resolve_fqdn, args=(fqdn, ip_file))
    thread.start()

thread.join()
